### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

### POST Register Users
# @name User/Create
POST http://localhost:3000/user
Content-Type:application/json

{
  "name": "Vitor Lamartine",
  "email": "vitor@teste.com",
  "password": "123",
  "confirmPassword": "1234"
}

### POST Login
# @name Auth/Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "vitor@teste.com",
  "password": "123"
}